name: Check and Build Document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
      - name: Spell Check
        uses: igsekor/pyspelling-any@v1.0.4
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: CV.tex
      - name: Generate DocX
        uses: docker://pandoc/latex:2.9
        with:
          args: --output=CV.docx CV.tex
      - name: Upload Files
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            CV.docx
            CV.pdf
       
